name: 5분 대기조 (Wake Up Service)

on:
  # 1. 스케줄러: 5분마다 실행 (Cron 문법)
  schedule:
    - cron: "*/5 * * * *"
  # 2. 수동 실행 버튼: 테스트용 (Actions 탭에서 클릭 가능)
  workflow_dispatch:

jobs:
  wake_up:
    runs-on: ubuntu-latest
    steps:
      - name: API 찌르기 (Curl)
        run: |
          # 리랭커 깨우기
          # 1번 타자
          curl -v -X GET https://freebird920-slat-reranker.hf.space/openapi.json \
            -H "Authorization: Bearer ${{ secrets.HF_READ_TOKEN }}"

          # 크롤러 깨우기
          curl -v -X GET https://freebird920-slat-crawler-master.hf.space/openapi.json \
             -H "Authorization: Bearer ${{ secrets.HF_READ_TOKEN }}"
          # 1번 타자
          curl -v -X GET https://freebird920-slat-crawler-1.hf.space/openapi.json \
             -H "Authorization: Bearer ${{ secrets.HF_READ_TOKEN }}"
          # 2번 타자
          curl -v -X GET https://freebird920-slat-crawler-2.hf.space/openapi.json \
             -H "Authorization: Bearer ${{ secrets.HF_READ_TOKEN }}"
          # 3번 타자
          curl -v -X GET https://freebird920-slat-crawler-3.hf.space/openapi.json \
             -H "Authorization: Bearer ${{ secrets.HF_READ_TOKEN }}"
          # 4번 타자
          curl -v -X GET https://freebird920-slat-crawler-4.hf.space/openapi.json \
             -H "Authorization: Bearer ${{ secrets.HF_READ_TOKEN }}"


          # 4번 타자
          curl -v -X GET https://freebird920-slat-reamer-hf-01.hf.space/openapi.json \
             -H "Authorization: Bearer ${{ secrets.HF_READ_TOKEN }}"
